/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TaskD;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chew
 */
public class assignJob extends javax.swing.JFrame {

    /**
     * Creates new form assignJob
     */
    private deliveryManCollection dlvMan = new deliveryManCollection();
    private deliveryMan list = new deliveryMan();
    deliveryMan info[] = dlvMan.collectInfo();
    ArrayList<order> detail = orderList();
    
    
    public assignJob() {
        initComponents();
        addRow();
        addDeliveryMan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order No", "Restaurant", "Statu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Delivery Man");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public class order{
        private String ID;
        private String rest;
        private String statu;
        
        public order(String ID, String rest, String statu){
            this.ID = ID;
            this.rest = rest;
            this.statu = statu;
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String value = (String)jComboBox1.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        DefaultComboBoxModel dm = (DefaultComboBoxModel)jComboBox1.getModel();
        
        if(jTable1.getSelectedRow() >= 0){
            String OD = (String)jTable1.getValueAt(jTable1.getSelectedRow(),0);
            String st = (String)jTable1.getValueAt(jTable1.getSelectedRow(),2);
            if(st == "pending"){
        
            for(int i =0; i < detail.size() ; i++){
               if(OD == detail.get(i).ID){ 
                    for (deliveryMan info1 : info) {
                        if (value == info1.getName()) {
                            detail.set(i, new order(detail.get(i).ID, detail.get(i).rest,"delivery"));
                            info1.setState("Delivery");
                            addDeliveryMan();
                            addRow();
                        }
                    }
                    if(value == "No avalible"){
                        JOptionPane.showMessageDialog(null,"No avalible delivery man NOW !!");
                    }    
               }       
            }
            }else{
                JOptionPane.showMessageDialog(null,"Please select order ONLY with pending status!!");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

   
    
    public ArrayList orderList(){
        ArrayList<order> detail = new ArrayList<order>();
        order d1 = new order("A123","Pat Kin Cafe","delivery");
        order d2 = new order("A124","Pat Kin Cafe","pending");
        order d3 = new order("C083","WayBack","pending");
        order d4 = new order("B003","Huat Chang","delivery");
        order d5 = new order("C084","WayBack","pending");
        order d6 = new order("B004","Huat Chang","pending");
        detail.add(d1);
        detail.add(d2);
        detail.add(d3);
        detail.add(d4);
        detail.add(d5);
        detail.add(d6);
        return detail;
    }
    
    public void addRow(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[3];
        model.setRowCount(0);
        for(int i = 0 ; i < detail.size();i++){
            if( detail.get(i).statu == "pending"){
            rowData[0] = detail.get(i).ID;
            rowData[1] = detail.get(i).rest;
            rowData[2] = detail.get(i).statu;
            model.addRow(rowData);
            }
        }
        for(int i = 0 ; i < detail.size();i++){
            if( detail.get(i).statu == "delivery"){
            rowData[0] = detail.get(i).ID;
            rowData[1] = detail.get(i).rest;
            rowData[2] = detail.get(i).statu;
            model.addRow(rowData);
            }
        }
    }
    
    public void addDeliveryMan(){
        DefaultComboBoxModel dm = (DefaultComboBoxModel)jComboBox1.getModel();
        Object element = new Object();
        dm.removeAllElements();
        for(int i = 0; i < info.length;i++){
            if(info[i].getState() == "Available"){
                element = info[i].getName();
                dm.addElement(element); 
            }
        }if(dm.getSize() == 0){
            dm.addElement("No avalible");
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(assignJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(assignJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(assignJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(assignJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new assignJob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
